### ISSUE TITLE
Combined Pan & Volume 2D Control for Mixer UI represented by single column

### ISSUE THREAD

**Issue by ericfont** [musescore/MuseScore_design#11]
I've modified my design #10 to based on the advice of @MikelNelson to use a single vertical column for gain instead of a triangle...here is a mockup representing different values of gain & panning:

 ![merged-volume-pan-mockup-2d-slider-single-column](https://cloud.githubusercontent.com/assets/6502474/25361411/f1717536-291b-11e7-83fa-dc34dae60f0f.png)

The operation would be the same as I described in #10.

**Comment by 12people** [comment]
@ericfont 
Honestly, I wouldn't know how to use this control (or even think it's clickable). Also, the labels are too tiny to be useful for the general population.

Anyway, please report this in MuseScore's issue tracker -- this tracker will be closing.

**Comment by ericfont** [comment]
I'll close this...i'm not getting enough people in favor.  My current best redesign is: https://musescore.org/en/node/100081#comment-705326
